version: "2"

services:
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    # Disable volumes in demo purposes
    # volumes:
    #   - sonarqube_conf:/opt/sonarqube/conf
    #   - sonarqube_data:/opt/sonarqube/data
    #   - sonarqube_extensions:/opt/sonarqube/extensions
    #   - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    ports:
      - "8000:8080"
    #volumes:
      # Needed to run docker inside docker
      #- /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SONAR_URL=http://sonarqube:9000
